Repository oomph-lib/oomph-lib, pull requests merged in 2021-09, with the labels that each got.

#42 Fix auto-generated title in Doxygen documentation.
  doc/doc.txt
Labels: documentation, tidy up

#44 Bug fixes (DoubleVector; OomphUtilities) and new features (MUMPS symmetry/ordering, Tetgen target volumes, and support for new METIS)
  src/generic/double_vector.cc
  src/generic/mumps_solver.cc
  src/generic/mumps_solver.h
  src/generic/oomph_utilities.h
  src/generic/partitioning.cc
  src/generic/partitioning.h
  src/meshes/refineable_tetgen_mesh.template.h
  src/meshes/tetgen_mesh.template.h
  src/navier_stokes/Tnavier_stokes_elements.h
Labels: sources, C++11

#50 Patch issue with 'delete'-d solve() function of ComplexDampedJacobi and parallel_self_test.py
  bin/parallel_self_test.py
  demo_drivers/multigrid/helmholtz_multigrid/validate.sh
  src/pml_helmholtz/complex_smoother.h
Labels: bug, sources

#52 Move to C++11: Add support for construction of Vectors using initialiser_lists
  src/generic/Vector.h
Labels: sources, C++11
