Repository oomph-lib/oomph-lib, pull requests merged in 2021-08, with the labels that each got.

#20 Convert key files to Markdown (e.g. README), split workflows by OS and add status badges
  .github/workflows/build-and-publish-docs.yaml
  .github/workflows/build-and-validate.yml
  .github/workflows/self-tests-macos.yaml
  .github/workflows/self-tests-ubuntu.yaml
  AUTHORS
  AUTHORS.md
  CHANGELOG.md
  COPYING
  INSTALL
  INSTALL.md
  NEWS
  NEWS.md
  README
  README.md
Labels: enhancement

#23 Add list of contributors to CONTRIBUTORS.md and update README.md.
  CONTRIBUTORS.md
  README.md
Labels: documentation, tidy up

#21 Add cronjob workflow to update copyright notice every year
  .github/workflows/update-copyright-licence.yaml
  bin/update_copyright_licence_header.sh
  src/generic/mesh_as_geometric_object.h
Labels: enhancement, workflow

#27 Explicitly demand C++11 support in build for macOS.
  bin/autogen_helpers.sh
  demo_drivers/poisson/two_d_poisson/two_d_poisson2_mesh.cc
  demo_drivers/solid/simple_shear/Makefile.am
  non_interactive_autogen.sh
Labels: bug, demo drivers, build

#29 Make minor corrections to CONTRIBUTING.md.
  CONTRIBUTING.md
Labels: documentation, tidy up

#32 Update the webpages
  doc/FAQ/FAQ.txt
  doc/Makefile.am
  doc/bugs/bugs.txt
  doc/change_log/Makefile.am
  doc/change_log/change_log.txt
  doc/change_log/final_svn_log_before_move_to_git.txt
  doc/coding_conventions/coding_conventions.txt
  doc/copyright/copyright.txt
  doc/doc.txt
  doc/download/Doxyfile
  doc/download/Makefile.am
  doc/download/download.txt
  doc/download/php/download-info.php
  doc/oomph-lib_header.html.template
  doc/people/people.txt
  doc/poisson/one_d_poisson/one_d_poisson_demo.txt
  doc/publications/publications.txt
  doc/subversion/Doxyfile
  doc/subversion/Makefile.am
  doc/subversion/subversion.txt
  doc/the_distribution/the_distribution.txt
Labels: documentation, tidy up

#30 Tidy up the tutorials that broke because of clang-format
  doc/interaction/fsi_collapsible_channel_adapt/fsi_collapsible_channel_adapt.txt
  doc/interaction/fsi_collapsible_channel_algebraic/fsi_chan_alg.txt
  doc/interaction/vmtk_fsi/vmtk_fsi.txt
  doc/linear_solvers/linear_solvers.txt
  doc/multi_physics/multi_domain_ref_b_convect/multi_domain_ref_b_convect.txt
  doc/navier_stokes/spine_channel/spine_channel.txt
Labels: documentation, small fix

#33 Update copyright notice script and apply to missed file
  bin/update_copyright_licence_header.sh
  doc/copyright/copyright.txt
Labels: small fix, scripts

#31 Make status badges point to the Actions page in the same repository.
  README.md
Labels: documentation, small fix

#34 Clarify connecting to GitHub via SSH in CONTRIBUTING.md
  CONTRIBUTING.md
Labels: documentation, small fix
