Repository oomph-lib/oomph-lib, pull requests merged in 2021-07, with the labels that each got.

#5 Add GitHub action for make and deploy docs
  .github/workflows/build-and-publish-docs.yml
  .nojekyll
  bin/website_install.sh
  non_interactive_autogen.sh
  website.gitignore
Labels: feature

#3 Updated .gitignore file
  .gitignore
Labels: enhancement

#9 Patch: updated the deletion of raw pointers in matrices.cc to use delete[].
  src/generic/matrices.cc
Labels: bug

#13 Removed redundant unstructured "shell" demo drivers.
  demo_drivers/shell/Makefile.am
  demo_drivers/shell/circular_plate/CircularPlate.1.ele
  demo_drivers/shell/circular_plate/CircularPlate.1.node
  demo_drivers/shell/circular_plate/CircularPlate.1.poly
  demo_drivers/shell/circular_plate/Makefile.am
  demo_drivers/shell/circular_plate/unstructured_clamped_circular_plate.cc
  demo_drivers/shell/circular_plate/validata/circular_plate.dat.gz
  demo_drivers/shell/circular_plate/validate.sh
  demo_drivers/shell/clamped_shell/Makefile.am
  demo_drivers/shell/clamped_shell/Rectangle_CirTube.1.ele
  demo_drivers/shell/clamped_shell/Rectangle_CirTube.1.node
  demo_drivers/shell/clamped_shell/Rectangle_CirTube.1.poly
  demo_drivers/shell/clamped_shell/unstructured_clamped_curved_shell.cc
  demo_drivers/shell/clamped_shell/validata/unstructured_curved_shell.dat.gz
  demo_drivers/shell/clamped_shell/validate.sh
  demo_drivers/shell/plate/Makefile.am
  demo_drivers/shell/plate/UnitPlate.1.ele
  demo_drivers/shell/plate/UnitPlate.1.node
  demo_drivers/shell/plate/UnitPlate.1.poly
  demo_drivers/shell/plate/unstructured_clamped_square_plate.cc
  demo_drivers/shell/plate/validata/unstructured_square_plate.dat.gz
  demo_drivers/shell/plate/validate.sh
Labels: small fix

#14 Disabled one_d_act_inhibit self-test from validate script.
  demo_drivers/reaction_diffusion/one_d_act_inhibit/validate.sh
Labels: bug

#1 Add GitHub action for make and validate
  .github/workflows/build-and-validate.yml
Labels: feature

#16 Cleaned up most of the broken documentation where problems arose from…
  bin/run_clang_format_on_all.sh
  config/configure_options/private_configure_options/xeon_biolaptop_mpi
  doc/meshes/mesh_from_inline_triangle_internal_boundaries/mesh_from_inline_triangle_internal_boundaries.txt
  doc/mpi/boussinesq_convection/boussinesq_convection.txt
  doc/navier_stokes/surface_theory/surface_theory.txt
  doc/poisson/fish_poisson2/fish_poisson2.txt
  doc/preconditioners/lgr_navier_stokes/lgr_navier_stokes.txt
Labels: documentation

#19 Fixed missing clamped shell in parent Makefile.am, one_d_act_inhibit validate.sh, and updated .gitignore
  .gitignore
  demo_drivers/reaction_diffusion/one_d_act_inhibit/validate.sh
  demo_drivers/shell/Makefile.am
Labels: bug, small fix
