Repository oomph-lib/oomph-lib, pull requests merged in 2023-12, with the labels that each got.

#109 Fix error estimator
  src/generic/error_estimator.cc
Labels: small fix, tidy up, sources, mpi

#106 Fix search
  doc/search_results/Makefile.am
  doc/search_results/search_results.txt
Labels: tidy up

#112 Development to main
  doc/search_results/Makefile.am
  doc/search_results/search_results.txt
  src/generic/error_estimator.cc
Labels: documentation

#98 Add vtu output capability to TetmeshFacetedSurface
  self_test/faceted_surface_vtu_output/Makefile.am
  self_test/faceted_surface_vtu_output/faceted_surface_vtu_output_tester.cc
  self_test/faceted_surface_vtu_output/spherical_tetmesh_faceted_surface.h
  self_test/faceted_surface_vtu_output/validate.sh
  src/generic/tet_mesh.h
Labels: feature, sources, self tests
